#pragma once

#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}



// Define Layers to 10
#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 10

#ifdef RGB_MATRIX_ENABLE

#   undef RGB_MATRIX_SPLIT
#   define RGB_MATRIX_SPLIT { 17, 17 }
#   define SPLIT_TRANSPORT_MIRROR
#   define SPLIT_LAYER_STATE_ENABLE
#   define SPLIT_MODS_ENABLE


#    define RGB_DISABLE_WHEN_USB_SUSPENDED true  // turn off effects when suspended
#    undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 100
#    define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS // Sets the default brightness value, if none has been set
// #    define RGB_MATRIX_VAL_STEP 4 // The value by which to increment the brightness per adjustment action

// // #    define RGB_MATRIX_HUE_STEP 8
// // #    define RGB_MATRIX_SAT_STEP 8
// // #    define RGB_MATRIX_VAL_STEP 8
// // #    define RGB_MATRIX_SPD_STEP 10
#define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING

// #    define DISABLE_RGB_MATRIX_ALPHAS_MODS
// #    define DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
// #    define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// // #    define DISABLE_RGB_MATRIX_BREATHING
// #    define DISABLE_RGB_MATRIX_BAND_SAT
// #    define DISABLE_RGB_MATRIX_BAND_VAL
// #    define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #    define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #    define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #    define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
// #    define DISABLE_RGB_MATRIX_CYCLE_ALL
// #    define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// #    define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #    define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
// #    define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
// #    define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #    define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #    define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
// #    define DISABLE_RGB_MATRIX_DUAL_BEACON
// #    define DISABLE_RGB_MATRIX_RAINBOW_BEACON
// #    define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// #    define DISABLE_RGB_MATRIX_RAINDROPS
// #    define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
// #    define DISABLE_RGB_MATRIX_HUE_BREATHING
// #    define DISABLE_RGB_MATRIX_HUE_PENDULUM
// #    define DISABLE_RGB_MATRIX_HUE_WAVE

// #    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
// #    define DISABLE_RGB_MATRIX_DIGITAL_RAIN
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #    define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #    define DISABLE_RGB_MATRIX_MULTISPLASH
// #    define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH

// #    define RGB_MATRIX_KEYPRESSES  // reacts to keypresses
// #    define RGB_MATRIX_ANIMATION_SPEED_DEFAULT UINT8_MAX / 2
// #    define RGB_MATRIX_ANIMATION_SPEED_SLOW RGB_MATRIX_ANIMATION_SPEED_DEFAULT / 4
// #    define RGB_MATRIX_ANIMATION_SPEED_SLOWER RGB_MATRIX_ANIMATION_SPEED_SLOW / 3
#endif